version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
      - FIREBASE_CONFIG=/app/firebase.json
    depends_on:
      - db

  admin:
    build: ./admin
    container_name: admin
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"
    environment:
      - BACKEND_URL=http://backend:8000
      - FIREBASE_CONFIG=/app/firebase.json
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
