name: Build Android APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Flet & Dependencies
        run: |
          pip install flet requests
          # Install requirements khusus folder frontend lo
          if [ -f frontend/requirements.txt ]; then pip install -r frontend/requirements.txt; fi

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build APK
        run: |
          # Jalanin build dari root folder proyek lo
          # Format: flet build apk [path_folder_aplikasi]
          flet build apk frontend

      - name: Upload APK Result
        uses: actions/upload-artifact@v4
        with:
          name: Wellbeing-App-Release
          path: build/apk/*.apk